import { AppSidebar } from "@/components/app-sidebar";
import { ThemeProvider } from "@/components/Providers";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import "@/styles/globals.css";

import { type Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

import { Toaster } from "@/components/ui/sonner"
import { auth } from "@/server/auth";
import { getWorkflowsForSidebar } from "@/server/actions/getWorkflows";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  const { workflows } = await getWorkflowsForSidebar();

  return (
    <html lang="en" className={`${spaceGrotesk.variable}`} suppressHydrationWarning >
      <body
        className={`${spaceGrotesk.className} bg-background text-foreground selection:text-background selection:bg-foreground`}
        suppressHydrationWarning
      >
                  <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

           <SidebarProvider defaultOpen={false} >
                 {session?.user && (
                   <AppSidebar 
                     initialWorkflows={workflows} 
                     user={{
                       avatar: session.user.image || '',
                       email: session.user.email || '',
                       name: session.user.name || '',
                     }}
                   />
                 )}
                      <main className="h-screen flex flex-col w-screen">
        <SidebarTrigger user={session && session.user ? true : false} />
        {children}
      </main>
      <Toaster />
           </SidebarProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
